# -- True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# -- Mouse support
set -g mouse on

# -- Pass through(escape sequences)
set -gq allow-passthrough on

# -- Sessions persistence
set -g detach-on-destroy off

# -- vim mode in tmux panes
set-window-option -g mode-keys vi

# -- Key bindings
set-option -g prefix2 none
unbind r        # refresh
unbind %        # vertical split
unbind v
bind v split-window -h -c "#{pane_current_path}"
unbind '"'      # horizontal split
unbind s
bind s split-window -v -c "#{pane_current_path}"
unbind [        # copy-mode
bind Escape copy-mode
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
unbind q        # display-panes
bind q kill-pane
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane    # drag using mouse

# -- Path environment
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

# -- TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'seebi/tmux-colors-solarized'

# -- Configure plugin
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @sessionx-bind 'o'

# -- Status bar
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=default,fg=white,bold]  #S },#{#[bg=default,fg=white]  #S }}"

# -- Initialize TPM (keep this line at the end of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'