scan_timeout = 100
# command_timeout = 500

format = """
$directory\
$git_branch\
$git_status
$character\
"""

palettes = "solarized"

[character]
success_symbol = "[>](fg: base0)"
error_symbol = "[>](bold fg:red)"
vimcmd_symbol = "[vi:](bold fg:yellow)"

[palettes.solarized]
base03 = "#002b36"
base02 = "#073642"
base01 = "#586e75"
base00 = "#657b83"
base0 = "#839496"
base1 = "#93a1a1"
base2 = "#eee8d5"
base3 = "#fdf6e3"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
orange = "#cb4b16"
red = "#dc322f"
violet = "#6c71c4"
yellow = "#b58900"